### ISSUE TITLE
[Bug] Logs stopped working

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-provider-ray#79]
Between `0.2.1-fix` and `0.3.0a5`, the logs stopped working. The goal of this ticket is to understand why and fix this.

**Comment by pankajkoti** [comment]
After having setup locally, I was not able to reproduce this issue. I could see the logs both in the Airflow UI & Ray cluster's dashboard in the corresponding job logs. I have [reported](https://astronomer.slack.com/archives/C061R9U81QB/p1729857865013949) my findings over Slack to our users & awaiting their confirmation.

Attached images depict a DAG run that runs a loop for 700 iterations with a 1 second sleep between each iteration & logs corresponding lines denoting the iteration number & sleep message. 
![Image](https://github.com/user-attachments/assets/b32900e6-6fda-43c5-9819-94cf094b9c47)
![Image](https://github.com/user-attachments/assets/e8a8bfff-29dd-4d9e-91cb-d5e7b9ecb86f)
