### ISSUE TITLE
[Bug] Timeout not working as expected

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-provider-ray#80]
The ticket https://github.com/astronomer/astro-provider-ray/pull/74 was not enough for running ray pipelines that take longer. When using 0.3.0a5, the tasks are still timing out after 10min running.

As part of this ticket, we need to create a ray pipeline that takes 20 min and ensure it does not time out after 10 minutes.

**Comment by pankajkoti** [comment]
After having setup locally, I was not able to reproduce this issue. Upon setting `job_timeout_seconds=0` for the `SubmitRayJob` I was able to see the job running longer than 10 mins. I have [reported](https://astronomer.slack.com/archives/C061R9U81QB/p1729857865013949) my findings over Slack to our users & awaiting their confirmation.

Attached is a DAG run that ran for 700s (~11.5 mins) from a DAG task that runs a loop for 700 iterations with a 1 second sleep between each iteration.
![Image](https://github.com/user-attachments/assets/b32900e6-6fda-43c5-9819-94cf094b9c47)
