### ISSUE TITLE
[Feature] Support dynamic configuration based on Airflow context

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-provider-ray#81]
The Ray provider 0.2.1 allowed users to define a hard-coded configuration to materialize the Kubernetes cluster. The goal with this ticket is to allow users to define a function that can receive the Airflow context and can be used to generate the configuration dynamically by using context properties. 

Previously, lots of progress was accomplished in the PR:
https://github.com/astronomer/astro-provider-ray/pull/67

We should:
- Create a representative DAG of this feature
- Make sure the implementation works as expected
- Have tests covering this behaviour

**Comment by phanikumv** [comment]
Related to #67

**Comment by tatiana** [comment]
To implement the feature I had to do many improvements on the provider itself that were not initially planned, and created individual PRs:
* #92
* #93
* #95
* #96
* #97
* #98
* #99
* #100
* #101
* #102
* #103
